name: extended_text_library
description: package library for extended_text and extended_text_field,provide common base class.
version: 9.0.0
homepage: https://github.com/fluttercandies/extended_text_library

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

